/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ReadrAnnotation {
        "text": string;
    }
    interface ReadrDonateButton {
    }
    interface ReadrFooter {
    }
    interface ReadrHeader {
    }
    interface ReadrLatestCoverages {
    }
    interface ShareNav {
    }
}
declare global {
    interface HTMLReadrAnnotationElement extends Components.ReadrAnnotation, HTMLStencilElement {
    }
    var HTMLReadrAnnotationElement: {
        prototype: HTMLReadrAnnotationElement;
        new (): HTMLReadrAnnotationElement;
    };
    interface HTMLReadrDonateButtonElement extends Components.ReadrDonateButton, HTMLStencilElement {
    }
    var HTMLReadrDonateButtonElement: {
        prototype: HTMLReadrDonateButtonElement;
        new (): HTMLReadrDonateButtonElement;
    };
    interface HTMLReadrFooterElement extends Components.ReadrFooter, HTMLStencilElement {
    }
    var HTMLReadrFooterElement: {
        prototype: HTMLReadrFooterElement;
        new (): HTMLReadrFooterElement;
    };
    interface HTMLReadrHeaderElement extends Components.ReadrHeader, HTMLStencilElement {
    }
    var HTMLReadrHeaderElement: {
        prototype: HTMLReadrHeaderElement;
        new (): HTMLReadrHeaderElement;
    };
    interface HTMLReadrLatestCoveragesElement extends Components.ReadrLatestCoverages, HTMLStencilElement {
    }
    var HTMLReadrLatestCoveragesElement: {
        prototype: HTMLReadrLatestCoveragesElement;
        new (): HTMLReadrLatestCoveragesElement;
    };
    interface HTMLShareNavElement extends Components.ShareNav, HTMLStencilElement {
    }
    var HTMLShareNavElement: {
        prototype: HTMLShareNavElement;
        new (): HTMLShareNavElement;
    };
    interface HTMLElementTagNameMap {
        "readr-annotation": HTMLReadrAnnotationElement;
        "readr-donate-button": HTMLReadrDonateButtonElement;
        "readr-footer": HTMLReadrFooterElement;
        "readr-header": HTMLReadrHeaderElement;
        "readr-latest-coverages": HTMLReadrLatestCoveragesElement;
        "share-nav": HTMLShareNavElement;
    }
}
declare namespace LocalJSX {
    interface ReadrAnnotation {
        "onToggle"?: (event: CustomEvent<any>) => void;
        "text"?: string;
    }
    interface ReadrDonateButton {
        "onClickButton"?: (event: CustomEvent<any>) => void;
    }
    interface ReadrFooter {
        "onAboutLinkClick"?: (event: CustomEvent<any>) => void;
        "onContactLinkClick"?: (event: CustomEvent<any>) => void;
        "onPrivacyLinkClick"?: (event: CustomEvent<any>) => void;
    }
    interface ReadrHeader {
        "onReadrLogoLinkClick"?: (event: CustomEvent<any>) => void;
    }
    interface ReadrLatestCoverages {
        "onClickCoverage"?: (event: CustomEvent<any>) => void;
    }
    interface ShareNav {
        "onShareFacebookLinkClick"?: (event: CustomEvent<any>) => void;
        "onShareLineLinkClick"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "readr-annotation": ReadrAnnotation;
        "readr-donate-button": ReadrDonateButton;
        "readr-footer": ReadrFooter;
        "readr-header": ReadrHeader;
        "readr-latest-coverages": ReadrLatestCoverages;
        "share-nav": ShareNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "readr-annotation": LocalJSX.ReadrAnnotation & JSXBase.HTMLAttributes<HTMLReadrAnnotationElement>;
            "readr-donate-button": LocalJSX.ReadrDonateButton & JSXBase.HTMLAttributes<HTMLReadrDonateButtonElement>;
            "readr-footer": LocalJSX.ReadrFooter & JSXBase.HTMLAttributes<HTMLReadrFooterElement>;
            "readr-header": LocalJSX.ReadrHeader & JSXBase.HTMLAttributes<HTMLReadrHeaderElement>;
            "readr-latest-coverages": LocalJSX.ReadrLatestCoverages & JSXBase.HTMLAttributes<HTMLReadrLatestCoveragesElement>;
            "share-nav": LocalJSX.ShareNav & JSXBase.HTMLAttributes<HTMLShareNavElement>;
        }
    }
}
