/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LatestCoverages {
    }
    interface ReadrDonateLink {
    }
    interface ReadrFooter {
    }
    interface ReadrHeader {
    }
    interface ShareNav {
    }
}
declare global {
    interface HTMLLatestCoveragesElement extends Components.LatestCoverages, HTMLStencilElement {
    }
    var HTMLLatestCoveragesElement: {
        prototype: HTMLLatestCoveragesElement;
        new (): HTMLLatestCoveragesElement;
    };
    interface HTMLReadrDonateLinkElement extends Components.ReadrDonateLink, HTMLStencilElement {
    }
    var HTMLReadrDonateLinkElement: {
        prototype: HTMLReadrDonateLinkElement;
        new (): HTMLReadrDonateLinkElement;
    };
    interface HTMLReadrFooterElement extends Components.ReadrFooter, HTMLStencilElement {
    }
    var HTMLReadrFooterElement: {
        prototype: HTMLReadrFooterElement;
        new (): HTMLReadrFooterElement;
    };
    interface HTMLReadrHeaderElement extends Components.ReadrHeader, HTMLStencilElement {
    }
    var HTMLReadrHeaderElement: {
        prototype: HTMLReadrHeaderElement;
        new (): HTMLReadrHeaderElement;
    };
    interface HTMLShareNavElement extends Components.ShareNav, HTMLStencilElement {
    }
    var HTMLShareNavElement: {
        prototype: HTMLShareNavElement;
        new (): HTMLShareNavElement;
    };
    interface HTMLElementTagNameMap {
        "latest-coverages": HTMLLatestCoveragesElement;
        "readr-donate-link": HTMLReadrDonateLinkElement;
        "readr-footer": HTMLReadrFooterElement;
        "readr-header": HTMLReadrHeaderElement;
        "share-nav": HTMLShareNavElement;
    }
}
declare namespace LocalJSX {
    interface LatestCoverages {
    }
    interface ReadrDonateLink {
    }
    interface ReadrFooter {
        "onAboutLinkClick"?: (event: CustomEvent<any>) => void;
        "onContactLinkClick"?: (event: CustomEvent<any>) => void;
        "onPrivacyLinkClick"?: (event: CustomEvent<any>) => void;
    }
    interface ReadrHeader {
        "onReadrLogoLinkClick"?: (event: CustomEvent<any>) => void;
    }
    interface ShareNav {
        "onShareFacebookLinkClick"?: (event: CustomEvent<any>) => void;
        "onShareLINELinkClick"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "latest-coverages": LatestCoverages;
        "readr-donate-link": ReadrDonateLink;
        "readr-footer": ReadrFooter;
        "readr-header": ReadrHeader;
        "share-nav": ShareNav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "latest-coverages": LocalJSX.LatestCoverages & JSXBase.HTMLAttributes<HTMLLatestCoveragesElement>;
            "readr-donate-link": LocalJSX.ReadrDonateLink & JSXBase.HTMLAttributes<HTMLReadrDonateLinkElement>;
            "readr-footer": LocalJSX.ReadrFooter & JSXBase.HTMLAttributes<HTMLReadrFooterElement>;
            "readr-header": LocalJSX.ReadrHeader & JSXBase.HTMLAttributes<HTMLReadrHeaderElement>;
            "share-nav": LocalJSX.ShareNav & JSXBase.HTMLAttributes<HTMLShareNavElement>;
        }
    }
}
